services:
  proxy:
    build:
      context: "../reverse_proxy/"
      dockerfile: Dockerfile
      args:
        - PORT=3000
        - CSR_FILE_PATH=cert/request.csr
        - CERT_FILE_PATH=cert/proxy-service.cert
        - PRIVATE_KEY_PATH=cert/proxy-service.key
        - PKI_HOST=localhost:5500
      target: final
      network: host
    ports:
      - "3000:3000"
    networks:
      - internal
      - public
    healthcheck:
      test: curl -k --fail https://proxy:3000/health || exit 1
      interval: 60s
      timeout: 30s
      retries: 5
      start_period: 30s
  auth:
    build:
      context: "../api/"
      dockerfile: Dockerfile
      args:
        - SERVICE_NAME=auth
        - PORT=6000
        - CSR_FILE_PATH=cert/request.csr
        - CERT_FILE_PATH=cert/auth-service.cert
        - PRIVATE_KEY_PATH=cert/auth-service.key
        - PKI_HOST=localhost:5500
      target: final
      network: host
    ports:
      - "6000"
    networks:
      - auth
      - internal
    depends_on:
      db-auth:
        condition: service_healthy
      proxy:
        condition: service_healthy
  account:
    build:
      context: "../api/"
      dockerfile: Dockerfile
      args:
        - SERVICE_NAME=account
        - PORT=8000
        - CSR_FILE_PATH=cert/request.csr
        - CERT_FILE_PATH=cert/account-service.cert
        - PRIVATE_KEY_PATH=cert/account-service.key
        - PKI_HOST=localhost:5500
      target: final
      network: host
    ports:
      - "8000"
    networks:
      - account
      - internal
    depends_on:
      db-account:
        condition: service_healthy
      proxy:
        condition: service_healthy
  games:
    build:
      context: "../api/"
      dockerfile: Dockerfile
      args:
        - SERVICE_NAME=games
        - PORT=3500
        - CSR_FILE_PATH=cert/request.csr
        - CERT_FILE_PATH=cert/games-service.cert
        - PRIVATE_KEY_PATH=cert/games-service.key
        - PKI_HOST=localhost:5500
      target: final
      network: host
    ports:
      - "3500"
    networks:
      - games
      - internal
    depends_on:
      db-games:
        condition: service_healthy
      proxy:
        condition: service_healthy
  # middleware service
  mail:
    build: "../middleware/mail/"
    ports:
      - "4000"
    networks:
      - internal

  steam-openid:
    build: 
      context: "../middleware/steam-openid/"
      args:
        - PORT=7000
        - SERVICE_NAME=steam-openid
        - CSR_FILE_PATH=cert/request.csr
        - CERT_FILE_PATH=cert/steam-middleware.cert
        - PRIVATE_KEY_PATH=cert/steam-middleware.key
        - PKI_HOST=localhost:5500
      network: host
    environment:
      - STEAM_API_KEY_FILE=/run/secrets/steam_api_key
    secrets:
       - steam_api_key
    # middleware/steam-openid/scripts/compose-entrypoint.sh
    entrypoint: "./scripts/compose-entrypoint.sh"
    ports:
      - "7000:7000"
    networks:
      - internal
      - public

  db-account:
    build: "./db/account/"
    ports:
      - "5432"
    networks:
      - account
    environment:
      - DB_USER=test
      - DB_PASSWORD_FILE=/run/secrets/db-account-secret
    secrets:
      - db-account-secret
    entrypoint: ./db/postgres-compose-entrypoint.sh
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "test"]
      timeout: 20s
      retries: 10
  db-auth:
    build: "./db/auth/"
    ports:
      - "5432"
    networks:
      - auth
    environment:
      - DB_USER=test
      - DB_PASSWORD_FILE=/run/secrets/db-auth-secret
    secrets:
      - db-auth-secret
    entrypoint: ./db/postgres-compose-entrypoint.sh
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "test"]
      timeout: 20s
      retries: 10

  db-games:
    build: "./db/games/"
    ports:
      - "5432"
    networks:
      - games
    environment:
      - DB_USER=test
      - DB_PASSWORD_FILE=/run/secrets/db-games-secret
    secrets:
      - db-games-secret
    entrypoint: ./db/postgres-compose-entrypoint.sh
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "test"]
      timeout: 20s
      retries: 10

networks:
  auth: {}
  account: {}
  games: {}
  internal: {}
  public: 
    driver: bridge

secrets:
  db-account-secret:
    file: './db/account/secret/db_password.txt'
  db-auth-secret:
    file: './db/auth/secret/db_password.txt'
  db-games-secret:
    file: './db/games/secret/db_password.txt'
  steam_api_key:
    file: '../middleware/steam-openid/secrets/steam_api_key.txt'