services:
  proxy:
    build:
      context: "../reverse_proxy/"
      dockerfile: Dockerfile
      args:
        - PORT=3000
        - PKI_HOST=localhost:5500
      target: final
      network: host
    ports:
      - "3000:3000"
    networks:
      - internal
      - public
    healthcheck:
      test: curl --fail http://proxy:3000/health || exit 1
      interval: 60s
      timeout: 30s
      retries: 5
      start_period: 30s
  auth:
    build:
      context: "../api/"
      dockerfile: Dockerfile
      args:
        - SERVICE_NAME=auth
        - PORT=6000
        - CSR_FILE_PATH=cert/request.csr
        - CERT_FILE_PATH=cert/auth-service.cert
        - PRIVATE_KEY_PATH=cert/auth-service.key
        - PKI_HOST=localhost:5500
      target: final
      network: host
    ports:
      - "6000"
    networks:
      - auth
      - internal
    depends_on:
      db-auth:
        condition: service_healthy
      proxy:
        condition: service_healthy
  account:
    build:
      context: "../api/"
      dockerfile: Dockerfile
      args:
        - SERVICE_NAME=account
        - PORT=8000
        - CSR_FILE_PATH=cert/request.csr
        - CERT_FILE_PATH=cert/account-service.cert
        - PRIVATE_KEY_PATH=cert/account-service.key
        - PKI_HOST=localhost:5500
      target: final
      network: host
    ports:
      - "8000"
    networks:
      - account
      - internal
    depends_on:
      db-account:
        condition: service_healthy
      proxy:
        condition: service_healthy
  games:
    build:
      context: "../api/"
      dockerfile: Dockerfile
      args:
        - SERVICE_NAME=games
        - PORT=3500
        - CSR_FILE_PATH=cert/request.csr
        - CERT_FILE_PATH=cert/games-service.cert
        - PRIVATE_KEY_PATH=cert/games-service.key
        - PKI_HOST=localhost:5500
      target: final
      network: host
    ports:
      - "3500"
    networks:
      - games
      - internal
    depends_on:
      db-games:
        condition: service_healthy
      proxy:
        condition: service_healthy
  # middleware service
  mail:
    build: "../middleware/mail/"
    ports:
      - "4000"
    networks:
      - internal

  steam-openid:
    build: 
      context: "../middleware/steam-openid/"
      args:
        - PORT=7000
        - SERVICE_NAME=steam-middleware
        - CSR_FILE_PATH=cert/request.csr
        - CERT_FILE_PATH=cert/steam-middleware.cert
        - PRIVATE_KEY_PATH=cert/steam-middleware.key
        - PKI_HOST=localhost:5500
      network: host
    ports:
      - "7000:700"
    networks:
      - internal
      - public

  db-account:
    build: "./db/account/"
    ports:
      - "5432"
    networks:
      - account
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "test"]
      timeout: 20s
      retries: 10
  db-auth:
    build: "./db/auth/"
    ports:
      - "5432"
    networks:
      - auth
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "test"]
      timeout: 20s
      retries: 10

  db-games:
    build: "./db/games/"
    ports:
      - "5432"
    networks:
      - games
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "test"]
      timeout: 20s
      retries: 10

networks:
  auth: {}
  account: {}
  games: {}
  internal: {}
  public: 
    driver: bridge
