services:
  cert-manager:
    build:
      context: "./"
      dockerfile: Dockerfile
      args:
        - CERT_FILE_PATH=cert/root-ca.cert
        - PRIVATE_KEY_PATH=cert/root-ca.key
        - PORT=5500
      target: final
    ports:
      - "5500:5500"
    networks:
      - public

networks:
  public: 
    driver: bridge